import Head from "next/head";

import GenericHTML from "@/components/GenericHTML/GenericHTML";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main id="main-content">
        <GenericHTML
          htmlContent={{
            value: `<p>Beatae gravida sodales! Habitasse conubia exercitation, potenti nobis dignissim, ducimus necessitatibus, ligula! Hendrerit placeat vel. Sapiente laudantium, aliquam tempus voluptates etiam vehicula, hymenaeos penatibus est incidunt, tempor? Minim, arcu adipisicing.</p><p>Alias erat illum dictumst, nostra, repudiandae fringilla molestiae massa porta quis facilis voluptatum consequuntur! Aenean primis quaerat sem, etiam quibusdam incididunt cupidatat hymenaeos tempor condimentum hic aute eros elementum sequi.</p><h3 id="list-heading" class="AccessibilityDemo_heading3__sSXEN">Popular holiday destinations</h3><ul aria-labelledby="list-heading"><li>Malaga</li><li>Honolulu</li><li><span lang="hu">Budapest</span></li><li>New York</li><li>Old York</li></ul><p>Veritatis commodi facilisis! Rutrum, pharetra eu beatae ullamcorper quis quia fugit numquam aliquet, illo, eos. Aperiam nisi donec aptent ante! Aliquam, interdum dictum duis, ipsam laoreet, mattis posuere id iste.</p><p><a href="https://www.sitecore.com">Sitecore</a> is a digital experience platform that helps you create, manage, and optimize customer experiences across all channels.</p><p>Aliquam, interdum dictum duis, ipsam laoreet, mattis posuere id iste. Quisque, facilisi! Quisquam, cumque! Quisquam, cumque! Quisquam, cumque!</p>`,
          }}
        />
      </main>
    </>
  );
}
